[workspace]
resolver = "2"
members = [
    "crates/treb",
    "crates/treb-gui",
]

[workspace.dependencies]
treb-gui = { path = "crates/treb-gui" }

serde = { version = "1", default-features = false }
serde_json = { version = "1", default-features = false }